# Generated by Django 3.0.3 on 2020-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
