# Generated by Django 3.0.3 on 2020-05-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
